POST http://132.145.76.61:3001/api/login HTTP/1.1
content-type: application/json

   {"email" : "admin", 
   "password" :"ab-1234567890"}

#
###
#
GET http://132.145.76.61:3001/api/employees/382 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYwMzcxMDM4MywiZXhwIjoxNjAzNzEzOTgzfQ.iqrN6FN36qkFiUO5BplnBBHVBV6xeCNtBsn85jvskJw
#
###
#
GET http://132.145.76.61:3001/api/employees?manage_id=320 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYwMzcxMDM4MywiZXhwIjoxNjAzNzEzOTgzfQ.iqrN6FN36qkFiUO5BplnBBHVBV6xeCNtBsn85jvskJw


